// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lpnbmhkjgrluqeerowne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwbmJtaGtqZ3JsdXFlZXJvd25lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MzcyNjIsImV4cCI6MjA2NzExMzI2Mn0.SsI_56OjJg7xJaX9XuPmbiICJfy1rzyO_QP1nv1bGJw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});